<?php

namespace App\Http\Requests\Category;

use Illuminate\Foundation\Http\FormRequest;

class CategoryStoreRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\Rule|array|string>
     */
    public function rules(): array
    {
        return [
            'name' => ['required', 'max:255'],
            'slug' => ['max:255', 'unique:categories,slug'],
            'description' => ['max:255'],
            'order' => ['integer'],
            'seo_keywords' => ['max:255'],
            'seo_description' => ['max:255'],
            'image' => ['nullable']
//            "image" => ['image', 'mimetypes:image/jpeg,image/jpg,image/png', "max:2048"]
        ];
    }
    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
